#pragma once
#include "Engine/Framework.h"
// 에디터(Application) 는 Core 서비스 + 캔버스/컴포넌트/시스템을 거의 다 만지므로
// umbrella 두 줄로 전부 가져온다.  Engine.lib 자체는 이 헤더를 PCH 에 박지 않는다.
#include "Engine/Core/CoreAll.h"
#include "Engine/GameFramework/GameFrameworkAll.h"
#include "Application.h"

#if JBRO_PLATFORM_WINDOWS && JBRO_EDITOR
#include "Editor/Editor.h"
#include "Editor/EditorSimulationGuard.h"
#include "Editor/Localization/EditorLocalizationKeys.h"
#include "Editor/Theme/EditorTheme.h"
#include "Editor/Gui/EditorGuiActions.h"
#include "Editor/ImItem/ImActionButton.h"
#include "Editor/ImItem/ImAssetField.h"
#include "Editor/ImItem/ImEnumCombo.h"
#include "Editor/ImItem/ImFieldLabel.h"
#include "Editor/ImItem/ImFilterCombo.h"
#include "Editor/ImItem/ImIconButton.h"
#include "Editor/ImItem/ImPathField.h"
#include "Editor/ImItem/ImReferenceField.h"
#include "Editor/ImItem/ImSearchBox.h"
#include "Editor/ImItem/ImSectionHeader.h"
#include "Editor/ImItem/ImStatusBadge.h"
#include "Editor/ImItem/ImValidationMessage.h"
#include "Editor/RootDockWindow.h"
#include "Editor/Main/MainDockWindow.h"

#include "Editor/Main/AssetBrowser/AssetBrowserTool.h"
#include "Editor/Main/Inspector/InspectorTool.h"
#include "Editor/Main/CanvasView/CanvasViewContour.h"
#include "Editor/Main/CanvasView/CanvasViewEditContext.h"
#include "Editor/Main/CanvasView/CanvasViewTool.h"
#include "Editor/Main/GameView/GameViewTool.h"
#include "Editor/Main/Log/LogTool.h"
#include "Editor/Main/Layers/LayerTool.h"
#include "Editor/Main/BuildSettingsWindow.h"
#include "Editor/Main/ProjectSettingsWindow.h"
#endif
