<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildThisFileDirectory)JBro.Common.props" Condition="'$(JBroRoot)' == ''" />

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(JBroScriptIncludes)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
