# KS X 1001(완성형)의 한글 음절 2,350 자를 코드포인트 표로 만든다(text-plan §3.6 의 prewarm).
#
# 완성형 한글은 EUC-KR 의 0xB0A1 ~ 0xC8FE (행 25 x 열 94)다. .NET 의 코드 페이지 949 로 풀어 유니코드 음절로 적는다.
# 생성물은 커밋한다 - 빌드는 이것을 돌리지 않는다.
#
#   pwsh Modules\JBroText\Source\GenerateKsx1001.ps1
$ErrorActionPreference = 'Stop'

[System.Text.Encoding]::RegisterProvider([System.Text.CodePagesEncodingProvider]::Instance)
$euckr = [System.Text.Encoding]::GetEncoding(949)
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$target = Join-Path $here 'Ksx1001Hangul.generated.h'

$codes = New-Object System.Collections.Generic.List[int]
for ($high = 0xB0; $high -le 0xC8; $high++)
{
    for ($low = 0xA1; $low -le 0xFE; $low++)
    {
        $text = $euckr.GetString([byte[]]@($high, $low))
        $codes.Add([int][char]$text[0])
    }
}
if ($codes.Count -ne 2350)
{
    throw "expected 2350 syllables, got $($codes.Count)"
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.Append("// Generated by Modules/JBroText/Source/GenerateKsx1001.ps1. Do not edit.`n")
[void]$builder.Append("// The 2,350 Hangul syllables of KS X 1001 (EUC-KR 0xB0A1-0xC8FE), in code order.`n")
[void]$builder.Append("#pragma once`n`n#include <cstdint>`n`n")
[void]$builder.Append("namespace JBro::Text::Detail`n{`n    inline constexpr std::uint16_t Ksx1001Hangul[] =`n    {`n")
for ($index = 0; $index -lt $codes.Count; $index += 12)
{
    $count = [Math]::Min(12, $codes.Count - $index)
    $row = for ($column = 0; $column -lt $count; $column++) { '0x{0:X4}' -f $codes[$index + $column] }
    [void]$builder.Append('        ' + ($row -join ', ') + ",`n")
}
[void]$builder.Append("    };`n}`n")
[System.IO.File]::WriteAllText($target, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "wrote $target ($($codes.Count) syllables)"
