# 시험 폰트를 테스트가 include 하는 바이트 배열 헤더로 만든다(D-200, text-plan §5 의 1 단계).
#
# 테스트가 실행 폴더를 기준으로 파일을 찾지 않게 하려고 바이트를 실행 파일에 넣는다 - 셰이더의 .generated.h 와 같은 방식이다.
# 생성물은 커밋한다.
#
#   pwsh Tests\Data\Fonts\Embed.ps1
$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$tests = Split-Path -Parent (Split-Path -Parent $here)
$source = Join-Path $here 'NotoSansKR-Subset.otf'
$target = Join-Path $tests 'TestFontNotoSansKR.generated.h'

$bytes = [System.IO.File]::ReadAllBytes($source)
$builder = [System.Text.StringBuilder]::new()
[void]$builder.Append("// Generated by Tests/Data/Fonts/Embed.ps1 from NotoSansKR-Subset.otf. Do not edit.`n")
[void]$builder.Append("// SIL Open Font License 1.1 - see Tests/Data/Fonts/OFL.txt.`n")
[void]$builder.Append("#pragma once`n`n")
[void]$builder.Append("inline constexpr unsigned char TestFontNotoSansKR[] =`n{`n")
for ($index = 0; $index -lt $bytes.Length; $index += 16)
{
    $count = [Math]::Min(16, $bytes.Length - $index)
    $row = for ($column = 0; $column -lt $count; $column++) { '0x{0:x2}' -f $bytes[$index + $column] }
    [void]$builder.Append('    ' + ($row -join ', ') + ",`n")
}
[void]$builder.Append("};`n")
[System.IO.File]::WriteAllText($target, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "wrote $target ($($bytes.Length) bytes)"
