# 공개 헤더마다 번역 단위를 하나씩 만든다.
#
# 한 번역 단위는 첫 include 하나의 자립성만 증명한다(D-53). 그래서 헤더 수만큼
# 파일이 필요하고, 손으로 유지할 수 없으니 여기서 만든다. 생성물은 커밋한다 —
# 빌드에 코드 생성 단계를 넣지 않기 위해서다.
#
#   pwsh Tests\HeaderSelfContainment\Generate.ps1
#
# 헤더를 더하거나 옮긴 뒤에 돌리고, 만들어진 .cpp 를 함께 커밋한다.
$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent (Split-Path -Parent $here)

# 이 플랫폼에서 컴파일되지 않는 헤더만 뺀다. 이유 없이 빼지 않는다.
$excluded = @{
    'JBro/Platform/AndroidPlatform.h' = 'Android NDK only'
    'JBro/Platform/WebPlatform.h'     = 'Emscripten only'
}

Get-ChildItem -Path $here -Filter '*.cpp' | Remove-Item

$headers = Get-ChildItem -Path (Join-Path $root 'Modules') -Recurse -Filter '*.h' |
    Where-Object { $_.FullName -match '\\Include\\JBro\\' } |
    ForEach-Object {
        $index = $_.FullName.IndexOf('\Include\')
        $_.FullName.Substring($index + 9).Replace('\', '/')
    } | Sort-Object

$written = 0
$skipped = @()
foreach ($header in $headers)
{
    if ($excluded.ContainsKey($header))
    {
        $skipped += "$header ($($excluded[$header]))"
        continue
    }
    $name = ($header -replace '^JBro/', '' -replace '\.h$', '' -replace '/', '_')
    $path = Join-Path $here "$name.cpp"
    $body = @"
// Generated by Generate.ps1. Do not edit.
//
// 이 번역 단위의 유일한 목적은 <$header> 가 혼자서 컴파일되는지 보는 것이다.
// 두 번 넣는 것은 재포함 방지가 실제로 도는지 함께 보기 위해서다.
#include <$header>
#include <$header>
"@
    Set-Content -Path $path -Value $body -Encoding utf8BOM
    $written++
}

"generated $written translation units"
foreach ($skip in $skipped)
{
    "skipped $skip"
}
