// Generated by Generate.ps1. Do not edit.
//
// 이 번역 단위의 유일한 목적은 <JBro/Package/PackageWriter.h> 가 혼자서 컴파일되는지 보는 것이다.
// 두 번 넣는 것은 재포함 방지가 실제로 도는지 함께 보기 위해서다.
#include <JBro/Package/PackageWriter.h>
#include <JBro/Package/PackageWriter.h>
